#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : natsort
Version  : 7.1.1
Release  : 21
URL      : https://files.pythonhosted.org/packages/06/73/132e1986f7d37826e39825097e09f2c86b1339609926210ebdaec74a3b72/natsort-7.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/06/73/132e1986f7d37826e39825097e09f2c86b1339609926210ebdaec74a3b72/natsort-7.1.1.tar.gz
Summary  : Simple yet flexible natural sorting in Python.
Group    : Development/Tools
License  : MIT
Requires: natsort-bin = %{version}-%{release}
Requires: natsort-license = %{version}-%{release}
Requires: natsort-python = %{version}-%{release}
Requires: natsort-python3 = %{version}-%{release}
Requires: PyICU
BuildRequires : PyICU
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
=======

%package bin
Summary: bin components for the natsort package.
Group: Binaries
Requires: natsort-license = %{version}-%{release}

%description bin
bin components for the natsort package.


%package license
Summary: license components for the natsort package.
Group: Default

%description license
license components for the natsort package.


%package python
Summary: python components for the natsort package.
Group: Default
Requires: natsort-python3 = %{version}-%{release}

%description python
python components for the natsort package.


%package python3
Summary: python3 components for the natsort package.
Group: Default
Requires: python3-core
Provides: pypi(natsort)

%description python3
python3 components for the natsort package.


%prep
%setup -q -n natsort-7.1.1
cd %{_builddir}/natsort-7.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1629298332
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/natsort
cp %{_builddir}/natsort-7.1.1/LICENSE %{buildroot}/usr/share/package-licenses/natsort/603b0cce2075f09251d99f7561d772373b456f21
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/natsort

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/natsort/603b0cce2075f09251d99f7561d772373b456f21

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
